from .gridid import GRIDID
from .issn import ISSN
from .stock_number import StockNumber
from .doi import DOI
from .swhid import SWHID
from .handle import HANDLE
from .identifiers_dot_org_id import IdentifiersDotOrgID
from .orcid import ORCID
from .isbn import ISBN
from .rrid import RRID
from .rorid import RORID
