"""
Structured information on a protocol execution.
"""

# this file was auto-generated!

from datetime import datetime, time

from openminds.base import LinkedMetadata
from openminds.properties import Property


class ProtocolExecution(LinkedMetadata):
    """
    Structured information on a protocol execution.
    """

    type_ = "https://openminds.ebrains.eu/core/ProtocolExecution"
    context = {"@vocab": "https://openminds.ebrains.eu/vocab/"}
    schema_version = "v2.0"

    properties = [
        Property(
            "behavioral_tasks",
            "openminds.v2.core.BehavioralTask",
            "behavioralTask",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Specific set of defined activities (or their absence) that should be performed (or avoided) by a subject.",
            instructions="Add all behavioral tasks that were performed during this protocol execution.",
        ),
        Property(
            "description",
            str,
            "description",
            formatting="text/markdown",
            multiline=True,
            description="Longer statement or account giving the characteristics of the protocol execution.",
            instructions="Enter a description of this activity.",
        ),
        Property(
            "ended_at_time",
            [datetime, time],
            "endedAtTime",
            description="no description available",
            instructions="Enter the time (e.g., '20:20:39+00:00') or datetime (e.g., '2018-11-13T20:20:39+00:00') of when the activity ended.",
        ),
        Property(
            "inputs",
            [
                "openminds.v2.core.File",
                "openminds.v2.core.FileBundle",
                "openminds.v2.core.SubjectGroupState",
                "openminds.v2.core.SubjectState",
                "openminds.v2.core.TissueSampleCollectionState",
                "openminds.v2.core.TissueSampleState",
            ],
            "input",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="Something or someone that is put into or participates in a process or machine.",
            instructions="Add all inputs used by this activity.",
        ),
        Property(
            "is_part_of",
            "openminds.v2.core.DatasetVersion",
            "isPartOf",
            required=True,
            description="Reference to the ensemble of multiple things or beings.",
            instructions="Add the dataset version in which this protocol execution was conducted.",
        ),
        Property(
            "lookup_label",
            str,
            "lookupLabel",
            formatting="text/plain",
            description="no description available",
            instructions="Enter a lookup label for this activity that may help you to more easily find it again.",
        ),
        Property(
            "outputs",
            [
                "openminds.v2.core.File",
                "openminds.v2.core.FileBundle",
                "openminds.v2.core.SubjectGroupState",
                "openminds.v2.core.SubjectState",
                "openminds.v2.core.TissueSampleCollectionState",
                "openminds.v2.core.TissueSampleState",
            ],
            "output",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="Something or someone that comes out of, is delivered or produced by a process or machine.",
            instructions="Add all outputs generated by this activity.",
        ),
        Property(
            "parameter_sets",
            "openminds.v2.core.ParameterSet",
            "parameterSet",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Manner, position, or direction in which digital or physical properties are set to determine a particular function, characteristics or behavior of something.",
            instructions="Add all important parameters grouped in context-specific sets that were used in this activity.",
        ),
        Property(
            "preparation_type",
            "openminds.v2.controlled_terms.PreparationType",
            "preparationType",
            description="Distinct class of actions or processes that make something ready for use or service.",
            instructions="Add the initial preparation type for this protocol execution.",
        ),
        Property(
            "protocols",
            "openminds.v2.core.Protocol",
            "protocol",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="Plan that describes the process of a scientific or medical experiment, treatment, or procedure.",
            instructions="Add all protocols that were used in this protocol execution.",
        ),
        Property(
            "started_at_time",
            [datetime, time],
            "startedAtTime",
            description="no description available",
            instructions="Enter the time (e.g., '20:20:39+00:00') or datetime (e.g., '2018-11-13T20:20:39+00:00') of when the activity started.",
        ),
        Property(
            "study_targets",
            [
                "openminds.v2.controlled_terms.AuditoryStimulusType",
                "openminds.v2.controlled_terms.BiologicalOrder",
                "openminds.v2.controlled_terms.BiologicalSex",
                "openminds.v2.controlled_terms.BreedingType",
                "openminds.v2.controlled_terms.CellCultureType",
                "openminds.v2.controlled_terms.CellType",
                "openminds.v2.controlled_terms.Disease",
                "openminds.v2.controlled_terms.DiseaseModel",
                "openminds.v2.controlled_terms.ElectricalStimulusType",
                "openminds.v2.controlled_terms.GeneticStrainType",
                "openminds.v2.controlled_terms.GustatoryStimulusType",
                "openminds.v2.controlled_terms.Handedness",
                "openminds.v2.controlled_terms.MolecularEntity",
                "openminds.v2.controlled_terms.OlfactoryStimulusType",
                "openminds.v2.controlled_terms.OpticalStimulusType",
                "openminds.v2.controlled_terms.Organ",
                "openminds.v2.controlled_terms.OrganismSubstance",
                "openminds.v2.controlled_terms.OrganismSystem",
                "openminds.v2.controlled_terms.Species",
                "openminds.v2.controlled_terms.SubcellularEntity",
                "openminds.v2.controlled_terms.TactileStimulusType",
                "openminds.v2.controlled_terms.TermSuggestion",
                "openminds.v2.controlled_terms.TissueSampleType",
                "openminds.v2.controlled_terms.UBERONParcellation",
                "openminds.v2.controlled_terms.VisualStimulusType",
                "openminds.v2.sands.CustomAnatomicalEntity",
                "openminds.v2.sands.ParcellationEntity",
            ],
            "studyTarget",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Structure or function that was targeted within a study.",
            instructions="Add all study targets of this activity.",
        ),
    ]

    def __init__(
        self,
        id=None,
        behavioral_tasks=None,
        description=None,
        ended_at_time=None,
        inputs=None,
        is_part_of=None,
        lookup_label=None,
        outputs=None,
        parameter_sets=None,
        preparation_type=None,
        protocols=None,
        started_at_time=None,
        study_targets=None,
    ):
        return super().__init__(
            id=id,
            behavioral_tasks=behavioral_tasks,
            description=description,
            ended_at_time=ended_at_time,
            inputs=inputs,
            is_part_of=is_part_of,
            lookup_label=lookup_label,
            outputs=outputs,
            parameter_sets=parameter_sets,
            preparation_type=preparation_type,
            protocols=protocols,
            started_at_time=started_at_time,
            study_targets=study_targets,
        )
