"""
Structured information on a protocol execution.
"""

# this file was auto-generated!


from openminds.base import LinkedMetadata
from openminds.properties import Property


class ProtocolExecution(LinkedMetadata):
    """
    Structured information on a protocol execution.
    """

    type_ = ["https://openminds.ebrains.eu/core/ProtocolExecution"]
    context = {"vocab": "https://openminds.ebrains.eu/vocab/"}

    properties = [
        Property(
            "description",
            str,
            "vocab:description",
            formatting="text/markdown",
            multiline=True,
            description="Longer statement or account giving the characteristics of someone or something.",
            instructions="Enter a description of this protocol execution.",
        ),
        Property(
            "input",
            [
                "openminds.v1_0.core.FileBundle",
                "openminds.v1_0.core.FileInstance",
                "openminds.v1_0.core.SubjectGroupState",
                "openminds.v1_0.core.SubjectState",
                "openminds.v1_0.core.TissueSampleCollectionState",
                "openminds.v1_0.core.TissueSampleState",
            ],
            "vocab:input",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="Something or someone that is put into or participates in a process or machine.",
            instructions="Add all inputs (subject state, tissue sample state, file instance or file bundle) used by this protocol execution.",
        ),
        Property(
            "output",
            [
                "openminds.v1_0.core.FileBundle",
                "openminds.v1_0.core.FileInstance",
                "openminds.v1_0.core.SubjectGroupState",
                "openminds.v1_0.core.SubjectState",
                "openminds.v1_0.core.TissueSampleCollectionState",
                "openminds.v1_0.core.TissueSampleState",
            ],
            "vocab:output",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="Something or someone that comes out of, is delivered or produced by a process or machine.",
            instructions="Add all outputs (subject state, tissue sample state, file instance or file bundle) generated by this protocol execution.",
        ),
        Property(
            "parameter_setting",
            "openminds.v1_0.core.ParameterSetting",
            "vocab:parameterSetting",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add all important parameter settings defining this protocol execution.",
        ),
        Property(
            "preparation_type",
            "openminds.v1_0.controlled_terms.PreparationType",
            "vocab:preparationType",
            description="Distinct class of actions or processes that make something ready for use or service.",
            instructions="Add the initial preparation type for this protocol execution.",
        ),
        Property(
            "protocol",
            "openminds.v1_0.core.Protocol",
            "vocab:protocol",
            required=True,
            description="Plan that describes the process of a scientific or medical experiment, treatment, or procedure.",
            instructions="Add the protocol of this protocol execution.",
        ),
        Property(
            "semantically_anchored_to",
            "openminds.v1_0.sands.AnatomicalEntity",
            "vocab:semanticallyAnchoredTo",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Reference to a related anatomical structure without providing a quantitative proof of the claimed relation.",
            instructions="Add all anatomical entities to which the outputs of this protocol execution can be semantically anchored to.",
        ),
        Property(
            "study_target",
            [
                "openminds.v1_0.controlled_terms.BiologicalSex",
                "openminds.v1_0.controlled_terms.Disease",
                "openminds.v1_0.controlled_terms.Genotype",
                "openminds.v1_0.controlled_terms.Phenotype",
                "openminds.v1_0.controlled_terms.Species",
                "openminds.v1_0.controlled_terms.TermSuggestion",
                "openminds.v1_0.sands.AnatomicalEntity",
            ],
            "vocab:studyTarget",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Structure or function that was targeted within a study.",
            instructions="Add all study targets of this model version.",
        ),
    ]

    def __init__(
        self,
        id=None,
        description=None,
        input=None,
        output=None,
        parameter_setting=None,
        preparation_type=None,
        protocol=None,
        semantically_anchored_to=None,
        study_target=None,
    ):
        return super().__init__(
            id=id,
            description=description,
            input=input,
            output=output,
            parameter_setting=parameter_setting,
            preparation_type=preparation_type,
            protocol=protocol,
            semantically_anchored_to=semantically_anchored_to,
            study_target=study_target,
        )
