"""
<description not available>
"""

# this file was auto-generated!

from numbers import Real

from openminds.base import LinkedMetadata
from openminds.properties import Property


class MRIScannerUsage(LinkedMetadata):
    """
    <description not available>
    """

    type_ = "https://openminds.om-i.org/types/MRIScannerUsage"
    context = {"@vocab": "https://openminds.om-i.org/props/"}
    schema_version = "latest"

    properties = [
        Property(
            "acceleration_factor",
            int,
            "accelerationFactor",
            description="no description available",
            instructions="Enter the acceleration factor (R), defined as the ratio of fully sampled to reduced k-space acquisition, with R ≥ 1 and R = 1 indicating no acceleration. This value is specified in the sequence protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "device",
            "openminds.latest.neuroimaging.MRIScanner",
            "device",
            required=True,
            description="Piece of equipment or mechanism (hardware) designed to serve a special purpose or perform a special function.",
            instructions="Add the MRI Scanner used.",
        ),
        Property(
            "diffusion_encoding_parameterss",
            "openminds.latest.core.File",
            "diffusionEncodingParameters",
            multiple=True,
            unique_items=False,
            min_items=2,
            max_items=2,
            description="no description available",
            instructions="Add two diffusion encoding files: a b-value file specifying the diffusion weighting for each acquired volume and a b-vector file specifying the corresponding three-dimensional diffusion gradient directions. Ensure that both files are correctly ordered, that b-vectors are normalized, and that they are aligned with the image volumes.",
        ),
        Property(
            "dwell_time",
            "openminds.latest.core.QuantitativeValue",
            "dwellTime",
            description="no description available",
            instructions="Enter the dwell time, defined as the time interval between successive data samples during signal readout, which determines the receiver bandwidth and frequency resolution. This value is typically set automatically by the sequence and can be retrieved from the sequence protocol or DICOM header.",
        ),
        Property(
            "echo_times",
            "openminds.latest.core.QuantitativeValue",
            "echoTime",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="no description available",
            instructions="Enter the echo time (TE), defined as the interval between the center of the excitation pulse and the center of the measured echo, expressed in milliseconds. This value is specified in the sequence protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "fat_suppression_technique",
            "openminds.latest.controlled_terms.MRIFatSuppressionTechnique",
            "fatSuppressionTechnique",
            description="no description available",
            instructions="Add the fat suppression technique used for this acquisition (for example, fat saturation, SPAIR, STIR, or Dixon); if no fat suppression was applied, leave this field null. This information is typically specified in the sequence protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "field_of_view",
            [],
            "fieldOfView",
            description="no description available",
            instructions="Add the field of view of this image.",
        ),
        Property(
            "flip_angle",
            "openminds.latest.core.QuantitativeValue",
            "flipAngle",
            description="no description available",
            instructions="Enter the flip angle, defined as the angle by which the net magnetization is rotated by the radiofrequency excitation pulse, expressed in degrees. This value is specified in the sequence protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "gradient_correction",
            "openminds.latest.controlled_terms.AnalysisTechnique",
            "gradientCorrection",
            description="no description available",
            instructions="Add the gradient correction method applied during image reconstruction. This information is typically defined by the scanner system and can be retrieved from the reconstruction settings or DICOM header.",
        ),
        Property(
            "inversion_time",
            "openminds.latest.core.QuantitativeValue",
            "inversionTime",
            description="no description available",
            instructions="Enter the inversion time (TI), defined as the interval between the inversion pulse and the excitation pulse, expressed in milliseconds. This value is specified in the sequence protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "lookup_label",
            str,
            "lookupLabel",
            formatting="text/plain",
            description="no description available",
            instructions="Enter a lookup label for this device usage that may help you to find this instance more easily.",
        ),
        Property(
            "matrix_sizes",
            int,
            "matrixSize",
            multiple=True,
            unique_items=False,
            min_items=2,
            max_items=3,
            description="no description available",
            instructions="Enter the matrix size as the number of samples in the frequency and phase encoding directions for two-dimensional acquisitions (frequency × phase), or in the frequency, phase, and partition encoding directions for three-dimensional acquisitions (frequency × phase × partitions). This information is defined by the acquisition protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "metadata_locations",
            ["openminds.latest.core.File", "openminds.latest.core.FileBundle"],
            "metadataLocation",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add all files or file bundles containing additional information about the usage of this device.",
        ),
        Property(
            "mri_weighting",
            "openminds.latest.controlled_terms.MRIWeighting",
            "MRIWeighting",
            description="no description available",
            instructions="Add the magnetic resonance imaging weighting type describing the dominant source of image contrast. This designation reflects the contrast determined by repetition time, echo time, and inversion time and can be identified from the sequence protocol.",
        ),
        Property(
            "mt_pulse_shape",
            "openminds.latest.controlled_terms.PulseShape",
            "MTPulseShape",
            description="no description available",
            instructions="Add the shape of the magnetization transfer (MT) radiofrequency (RF) pulse waveform used in this acquisition. This information is specified in the sequence protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "number_of_discarded_volumes",
            int,
            "numberOfDiscardedVolumes",
            description="no description available",
            instructions="Enter the number of initial volumes automatically discarded by the scanner before saving data, typically to allow signal stabilization at the beginning of the acquisition. This value is defined by the acquisition protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "number_of_excitations",
            int,
            "numberOfExcitations",
            description="no description available",
            instructions="Enter the number of excitations (NEX), defined as the number of times each k-space line is acquired and averaged to improve signal-to-noise ratio; if no averaging was performed, set this value to 1. This value is specified in the acquisition protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "number_of_slices",
            int,
            "numberOfSlices",
            description="no description available",
            instructions="Enter the number of slices corresponding to the total number of two-dimensional image slices acquired in this scan. This value is defined by the acquisition protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "parallel_acquisition_technique",
            "openminds.latest.controlled_terms.MRIParallelAcquisitionTechnique",
            "parallelAcquisitionTechnique",
            description="no description available",
            instructions="Add the parallel acquisition technique used for this scan (for example, SENSE or GRAPPA). This information is specified in the sequence protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "phase_encoding_directions",
            int,
            "phaseEncodingDirection",
            multiple=True,
            unique_items=False,
            min_items=3,
            max_items=3,
            description="no description available",
            instructions="Enter the phase encoding direction as a signed unit vector in the scanner or image coordinate system (for example, [±1, 0, 0], [0, ±1, 0], or [0, 0, ±1]), where the nonzero component indicates the encoding axis and the sign specifies the polarity of k-space traversal.",
        ),
        Property(
            "receiver_bandwidth",
            "openminds.latest.core.QuantitativeValue",
            "receiverBandwidth",
            description="no description available",
            instructions="Enter the receiver bandwidth, defined as the range of frequencies sampled per pixel during signal acquisition, expressed in hertz per pixel. This value is specified in the sequence protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "repetition_time",
            "openminds.latest.core.QuantitativeValue",
            "repetitionTime",
            required=True,
            description="no description available",
            instructions="Enter the repetition time (TR), defined as the interval between successive excitation pulses, expressed in milliseconds. This value is specified in the sequence protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "slice_angulations",
            Real,
            "sliceAngulation",
            multiple=True,
            unique_items=False,
            min_items=3,
            max_items=3,
            description="no description available",
            instructions="Enter the slice plane orientation as a three-element unit normal vector [nx, ny, nz] in scanner coordinates, where each component is a dimensionless floating-point value between -1 and +1 and the vector has unit length (nx² + ny² + nz² = 1). For non-oblique acquisitions, the vector aligns with a principal axis (for example, [0, 0, 1]), and for oblique acquisitions, the components are fractional.",
        ),
        Property(
            "slice_gap",
            ["openminds.latest.core.QuantitativeValue", "openminds.latest.core.QuantitativeValueRange"],
            "sliceGap",
            description="no description available",
            instructions="Enter the slice gap, defined as the distance between adjacent slices, expressed in millimeters and excluding the slice thickness; if slice spacing is uniform, provide a single value, and if it varies across the volume, provide the corresponding range. This information is specified in the acquisition protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "slice_orientation",
            "openminds.latest.controlled_terms.AnatomicalPlane",
            "sliceOrientation",
            description="no description available",
            instructions="Add the primary slice plane, defined relative to the scanner coordinate system, where axial corresponds to planes perpendicular to the scanner z-axis, sagittal to planes perpendicular to the x-axis, and coronal to planes perpendicular to the y-axis. This classification is independent of subject orientation and may therefore differ from anatomical planes when the subject is positioned non-standardly in the scanner.",
        ),
        Property(
            "slice_thickness",
            ["openminds.latest.core.QuantitativeValue", "openminds.latest.core.QuantitativeValueRange"],
            "sliceThickness",
            description="no description available",
            instructions="Enter the slice thickness, defined as the physical thickness of each acquired slice, expressed in millimeters; if uniform, provide a single value, and if variable, provide the corresponding range. This value is specified in the acquisition protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "slice_timing",
            "openminds.latest.core.QuantitativeValueArray",
            "sliceTiming",
            required=True,
            description="no description available",
            instructions="Enter the slice timing, defined as the acquisition time of each slice within a volume relative to the start of the volume acquisition. This information is determined by the sequence timing and can be retrieved from the DICOM header.",
        ),
        Property(
            "spatial_encoding",
            "openminds.latest.controlled_terms.SpatialEncoding",
            "spatialEncoding",
            description="no description available",
            instructions="Add the spatial encoding scheme used to acquire the data, specifying how frequency, phase, and partition encoding were applied (for example, frequency–phase encoding for two-dimensional acquisitions or frequency–phase–phase encoding for three-dimensional acquisitions). This information is defined in the sequence protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "spoiling_technique",
            "openminds.latest.controlled_terms.MRISpoilingTechnique",
            "spoilingTechnique",
            description="no description available",
            instructions="Add the spoiling technique used in this acquisition, specifying the method applied to eliminate residual transverse magnetization (for example, radiofrequency spoiling or gradient spoiling). This information is defined in the sequence protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "total_read_out_time",
            "openminds.latest.core.QuantitativeValue",
            "totalReadOutTime",
            description="no description available",
            instructions="Enter the total readout time (TRT), defined as the time interval between acquisition of the first and last k-space lines in the phase-encoding direction during a single readout, expressed in milliseconds. This value is typically computed automatically and can be retrieved from the DICOM header.",
        ),
        Property(
            "transmitter_bandwidth",
            "openminds.latest.core.QuantitativeValue",
            "transmitterBandwidth",
            description="no description available",
            instructions="Enter the transmitter bandwidth, defined as the frequency range excited by the radiofrequency pulse per pixel, expressed in hertz per pixel. This value is specified in the sequence protocol and can be retrieved from the DICOM header.",
        ),
        Property(
            "used_coilss",
            ["openminds.latest.controlled_terms.DeviceType", "openminds.latest.neuroimaging.MRICoilUsage"],
            "usedCoils",
            multiple=True,
            unique_items=False,
            min_items=2,
            description="no description available",
            instructions="Add all coils used for this acquisition, including built-in and external transmit, receive, and gradient-related coils, corresponding to the relevant DICOM coil attributes. Preferably provide structured coil descriptions; if unavailable, specify at least the device type.",
        ),
        Property(
            "used_specimen",
            ["openminds.latest.core.SubjectState", "openminds.latest.core.TissueSampleState"],
            "usedSpecimen",
            description="no description available",
            instructions="Add the state of the tissue sample or subject that this device was used on.",
        ),
        Property(
            "voxel_size",
            "openminds.latest.core.QuantitativeValueArray",
            "voxelSize",
            description="Extent of the discrete elements comprising a three-dimensional entity.",
            instructions="Enter the voxel size as the physical dimensions of a single image voxel in the x, y, and z directions, expressed in millimeters. This value is typically derived from the field of view, matrix size, and slice thickness and can be retrieved from the DICOM header.",
        ),
    ]

    def __init__(
        self,
        id=None,
        acceleration_factor=None,
        device=None,
        diffusion_encoding_parameterss=None,
        dwell_time=None,
        echo_times=None,
        fat_suppression_technique=None,
        field_of_view=None,
        flip_angle=None,
        gradient_correction=None,
        inversion_time=None,
        lookup_label=None,
        matrix_sizes=None,
        metadata_locations=None,
        mri_weighting=None,
        mt_pulse_shape=None,
        number_of_discarded_volumes=None,
        number_of_excitations=None,
        number_of_slices=None,
        parallel_acquisition_technique=None,
        phase_encoding_directions=None,
        receiver_bandwidth=None,
        repetition_time=None,
        slice_angulations=None,
        slice_gap=None,
        slice_orientation=None,
        slice_thickness=None,
        slice_timing=None,
        spatial_encoding=None,
        spoiling_technique=None,
        total_read_out_time=None,
        transmitter_bandwidth=None,
        used_coilss=None,
        used_specimen=None,
        voxel_size=None,
    ):
        return super().__init__(
            id=id,
            acceleration_factor=acceleration_factor,
            device=device,
            diffusion_encoding_parameterss=diffusion_encoding_parameterss,
            dwell_time=dwell_time,
            echo_times=echo_times,
            fat_suppression_technique=fat_suppression_technique,
            field_of_view=field_of_view,
            flip_angle=flip_angle,
            gradient_correction=gradient_correction,
            inversion_time=inversion_time,
            lookup_label=lookup_label,
            matrix_sizes=matrix_sizes,
            metadata_locations=metadata_locations,
            mri_weighting=mri_weighting,
            mt_pulse_shape=mt_pulse_shape,
            number_of_discarded_volumes=number_of_discarded_volumes,
            number_of_excitations=number_of_excitations,
            number_of_slices=number_of_slices,
            parallel_acquisition_technique=parallel_acquisition_technique,
            phase_encoding_directions=phase_encoding_directions,
            receiver_bandwidth=receiver_bandwidth,
            repetition_time=repetition_time,
            slice_angulations=slice_angulations,
            slice_gap=slice_gap,
            slice_orientation=slice_orientation,
            slice_thickness=slice_thickness,
            slice_timing=slice_timing,
            spatial_encoding=spatial_encoding,
            spoiling_technique=spoiling_technique,
            total_read_out_time=total_read_out_time,
            transmitter_bandwidth=transmitter_bandwidth,
            used_coilss=used_coilss,
            used_specimen=used_specimen,
            voxel_size=voxel_size,
        )
