"""
Structured information on a protocol execution.
"""

# this file was auto-generated!


from openminds.base import LinkedMetadata
from openminds.properties import Property


class ProtocolExecution(LinkedMetadata):
    """
    Structured information on a protocol execution.
    """

    type_ = "https://openminds.ebrains.eu/core/ProtocolExecution"
    context = {"@vocab": "https://openminds.ebrains.eu/vocab/"}

    properties = [
        Property(
            "description",
            str,
            "description",
            formatting="text/markdown",
            multiline=True,
            description="Longer statement or account giving the characteristics of someone or something.",
            instructions="Enter a description of this protocol execution.",
        ),
        Property(
            "input",
            [
                "openminds.v2_0.core.FileBundle",
                "openminds.v2_0.core.File",
                "openminds.v2_0.core.SubjectGroupState",
                "openminds.v2_0.core.SubjectState",
                "openminds.v2_0.core.TissueSampleCollectionState",
                "openminds.v2_0.core.TissueSampleState",
            ],
            "input",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="Something or someone that is put into or participates in a process or machine.",
            instructions="Add all inputs (subject state, tissue sample state, file instance or file bundle) used by this protocol execution.",
        ),
        Property(
            "lookup_label",
            str,
            "lookupLabel",
            formatting="text/plain",
            description="no description available",
            instructions="Enter a lookup label for this protocol execution that may help you to more easily find it again.",
        ),
        Property(
            "output",
            [
                "openminds.v2_0.core.FileBundle",
                "openminds.v2_0.core.File",
                "openminds.v2_0.core.SubjectGroupState",
                "openminds.v2_0.core.SubjectState",
                "openminds.v2_0.core.TissueSampleCollectionState",
                "openminds.v2_0.core.TissueSampleState",
            ],
            "output",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="Something or someone that comes out of, is delivered or produced by a process or machine.",
            instructions="Add all outputs (subject state, tissue sample state, file instance or file bundle) generated by this protocol execution.",
        ),
        Property(
            "parameter_set",
            "openminds.v2_0.core.ParameterSet",
            "parameterSet",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Manner, position, or direction in which digital or physical properties are set to determine a particular function, characteristics or behavior of something.",
            instructions="Add all important parameters grouped in context-specific sets that were used in this protocol execution.",
        ),
        Property(
            "preparation_type",
            "openminds.v2_0.controlled_terms.PreparationType",
            "preparationType",
            description="Distinct class of actions or processes that make something ready for use or service.",
            instructions="Add the initial preparation type for this protocol execution.",
        ),
        Property(
            "protocol",
            "openminds.v2_0.core.Protocol",
            "protocol",
            required=True,
            description="Plan that describes the process of a scientific or medical experiment, treatment, or procedure.",
            instructions="Add the protocol of this protocol execution.",
        ),
        Property(
            "semantically_anchored_to",
            "openminds.v2_0.sands.AnatomicalEntity",
            "semanticallyAnchoredTo",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Reference to a related anatomical structure without providing a quantitative proof of the claimed relation.",
            instructions="Add all anatomical entities to which the outputs of this protocol execution can be semantically anchored to.",
        ),
        Property(
            "study_target",
            [
                "openminds.v2_0.controlled_terms.BiologicalSex",
                "openminds.v2_0.controlled_terms.CellType",
                "openminds.v2_0.controlled_terms.Disease",
                "openminds.v2_0.controlled_terms.DiseaseModel",
                "openminds.v2_0.controlled_terms.Handedness",
                "openminds.v2_0.controlled_terms.Organ",
                "openminds.v2_0.controlled_terms.Phenotype",
                "openminds.v2_0.controlled_terms.Species",
                "openminds.v2_0.controlled_terms.Strain",
                "openminds.v2_0.controlled_terms.TermSuggestion",
                "openminds.v2_0.sands.CustomAnatomicalEntity",
                "openminds.v2_0.sands.ParcellationEntity",
            ],
            "studyTarget",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Structure or function that was targeted within a study.",
            instructions="Add all study targets of this model version.",
        ),
    ]

    def __init__(
        self,
        id=None,
        description=None,
        input=None,
        lookup_label=None,
        output=None,
        parameter_set=None,
        preparation_type=None,
        protocol=None,
        semantically_anchored_to=None,
        study_target=None,
    ):
        return super().__init__(
            id=id,
            description=description,
            input=input,
            lookup_label=lookup_label,
            output=output,
            parameter_set=parameter_set,
            preparation_type=preparation_type,
            protocol=protocol,
            semantically_anchored_to=semantically_anchored_to,
            study_target=study_target,
        )
