"""
<description not available>
"""

# this file was auto-generated!

from datetime import date
from openminds.base import IRI

from openminds.base import LinkedMetadata
from openminds.properties import Property


class SoftwareVersion(LinkedMetadata):
    """
    <description not available>
    """

    type_ = "https://openminds.om-i.org/types/SoftwareVersion"
    context = {"@vocab": "https://openminds.om-i.org/props/"}
    schema_version = "latest"

    properties = [
        Property(
            "accessibility",
            "openminds.latest.core.Accessibility",
            "accessibility",
            required=True,
            description="Level to which something is accessible to the software version.",
            instructions="Add the accessibility of the data for this research product version.",
        ),
        Property(
            "contributions",
            "openminds.latest.core.Contribution",
            "contribution",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="no description available",
            instructions="Add all individual, organisational, or consortial contributions to this research product version. These values override the inherited values from the version-independent product.",
        ),
        Property(
            "contributor_affiliations",
            "openminds.latest.core.Affiliation",
            "contributorAffiliation",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add all affiliations for the individual contributors to this research product version.",
        ),
        Property(
            "copyright",
            "openminds.latest.core.Copyright",
            "copyright",
            description="Exclusive and assignable legal right of an originator to reproduce, publish, sell, or distribute the matter and form of a creative work for a defined time period.",
            instructions="Enter the copyright information of this research product version.",
        ),
        Property(
            "dependencys",
            "openminds.latest.core.Dependency",
            "dependency",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add all operating devices compatible with this software version.",
        ),
        Property(
            "description",
            str,
            "description",
            formatting="text/markdown",
            multiline=True,
            required=True,
            description="Longer statement or account giving the characteristics of the software version.",
            instructions="Enter a description (or abstract) of this research product version. This value overrides the inherited value from the version-independent product.",
        ),
        Property(
            "digital_identifier",
            [
                "openminds.latest.core.DOI",
                "openminds.latest.core.GenericIdentifier",
                "openminds.latest.core.RRID",
                "openminds.latest.core.SWHID",
            ],
            "digitalIdentifier",
            description="Digital handle to identify objects or legal persons.",
            instructions="Add the globally unique and persistent digital identifier of this research product version.",
        ),
        Property(
            "documentation",
            [
                "openminds.latest.core.DOI",
                "openminds.latest.core.File",
                "openminds.latest.core.ISBN",
                "openminds.latest.core.WebResource",
            ],
            "documentation",
            required=True,
            description="no description available",
            instructions="Add the publication or file that acts as the documentation of this research product version. This value overrides the inherited value from the version-independent product.",
        ),
        Property(
            "full_name",
            str,
            "fullName",
            formatting="text/plain",
            required=True,
            description="Whole, non-abbreviated name of the software version.",
            instructions="Enter a descriptive full name (or title) for this research product version. This value overrides the inherited value from the version-independent product.",
        ),
        Property(
            "funding",
            "openminds.latest.core.Funding",
            "funding",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Money provided by a legal person for a particular purpose.",
            instructions="Add all funding information of this research product version.",
        ),
        Property(
            "homepage",
            IRI,
            "homepage",
            description="Main website of the software version.",
            instructions="Enter the internationalized resource identifier (IRI) to the homepage of this research product version. This value overrides the inherited value from the version-independent product.",
        ),
        Property(
            "how_to_cite",
            str,
            "howToCite",
            formatting="text/markdown",
            multiline=True,
            description="Preferred format for citing a particular object or legal person.",
            instructions="Enter the preferred citation text for this research product version. Leave blank if citation text can be extracted from the assigned digital identifier.",
        ),
        Property(
            "implementss",
            "openminds.latest.core.InterfaceVersion",
            "implements",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add all interface versions that are implemented by this software version.",
        ),
        Property(
            "input_formats",
            "openminds.latest.core.ContentType",
            "inputFormat",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Format of data that is put into a process or machine.",
            instructions="Add all content types that can be used as input by this software version.",
        ),
        Property(
            "is_preceded_by",
            "openminds.latest.core.SoftwareVersion",
            "isPrecededBy",
            description="no description available",
            instructions="Add the software version preceding this software version.",
        ),
        Property(
            "is_variant_of",
            "openminds.latest.core.SoftwareVersion",
            "isVariantOf",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add all software versions that can be used alternatively to this software version.",
        ),
        Property(
            "is_version_of",
            "openminds.latest.core.Software",
            "isVersionOf",
            required=True,
            description="no description available",
            instructions="Add the version-independent information about this software.",
        ),
        Property(
            "keywords",
            [
                "openminds.latest.controlled_terms.AccessChannel",
                "openminds.latest.controlled_terms.AccessEligibilityType",
                "openminds.latest.controlled_terms.AccessForm",
                "openminds.latest.controlled_terms.AccessProcessType",
                "openminds.latest.controlled_terms.ActionStatusType",
                "openminds.latest.controlled_terms.AgeCategory",
                "openminds.latest.controlled_terms.AgeReference",
                "openminds.latest.controlled_terms.AnalysisTechnique",
                "openminds.latest.controlled_terms.AnatomicalAxesOrientation",
                "openminds.latest.controlled_terms.AnatomicalCavity",
                "openminds.latest.controlled_terms.AnatomicalIdentificationType",
                "openminds.latest.controlled_terms.AnatomicalPlane",
                "openminds.latest.controlled_terms.AnnotationCriteriaType",
                "openminds.latest.controlled_terms.AnnotationType",
                "openminds.latest.controlled_terms.AtlasType",
                "openminds.latest.controlled_terms.AuditoryStimulusType",
                "openminds.latest.controlled_terms.BiologicalOrder",
                "openminds.latest.controlled_terms.BiologicalProcess",
                "openminds.latest.controlled_terms.BiologicalSex",
                "openminds.latest.controlled_terms.BreedingType",
                "openminds.latest.controlled_terms.CellCultureType",
                "openminds.latest.controlled_terms.CellType",
                "openminds.latest.controlled_terms.ChemicalMixtureType",
                "openminds.latest.controlled_terms.Colormap",
                "openminds.latest.controlled_terms.CommunicationInterfaceType",
                "openminds.latest.controlled_terms.CommunicationProtocol",
                "openminds.latest.controlled_terms.ContributionType",
                "openminds.latest.controlled_terms.CranialWindowConstructionType",
                "openminds.latest.controlled_terms.CranialWindowReinforcementType",
                "openminds.latest.controlled_terms.CriteriaQualityType",
                "openminds.latest.controlled_terms.DataType",
                "openminds.latest.controlled_terms.DependencyImpact",
                "openminds.latest.controlled_terms.DeploymentEnvironmentType",
                "openminds.latest.controlled_terms.DeviceMountingType",
                "openminds.latest.controlled_terms.DeviceType",
                "openminds.latest.controlled_terms.DifferenceMeasure",
                "openminds.latest.controlled_terms.Disease",
                "openminds.latest.controlled_terms.DiseaseModel",
                "openminds.latest.controlled_terms.EducationalLevel",
                "openminds.latest.controlled_terms.ElectricalStimulusType",
                "openminds.latest.controlled_terms.ExperimentalApproach",
                "openminds.latest.controlled_terms.ExternalBodyRegion",
                "openminds.latest.controlled_terms.FileBundleGrouping",
                "openminds.latest.controlled_terms.FileRepositoryType",
                "openminds.latest.controlled_terms.FileUsageRole",
                "openminds.latest.controlled_terms.GeneticStrainType",
                "openminds.latest.controlled_terms.GustatoryStimulusType",
                "openminds.latest.controlled_terms.Handedness",
                "openminds.latest.controlled_terms.Language",
                "openminds.latest.controlled_terms.Laterality",
                "openminds.latest.controlled_terms.LearningResourceType",
                "openminds.latest.controlled_terms.MRIFatSuppressionTechnique",
                "openminds.latest.controlled_terms.MRIParallelAcquisitionTechnique",
                "openminds.latest.controlled_terms.MRIPulseSequence",
                "openminds.latest.controlled_terms.MRISpoilingTechnique",
                "openminds.latest.controlled_terms.MRIWeighting",
                "openminds.latest.controlled_terms.MeasuredQuantity",
                "openminds.latest.controlled_terms.MeasuredSignalType",
                "openminds.latest.controlled_terms.MetaDataModelType",
                "openminds.latest.controlled_terms.ModelAbstractionLevel",
                "openminds.latest.controlled_terms.ModelScope",
                "openminds.latest.controlled_terms.ModificationConsentRequirement",
                "openminds.latest.controlled_terms.ModificationConstraint",
                "openminds.latest.controlled_terms.ModificationForm",
                "openminds.latest.controlled_terms.ModificationScope",
                "openminds.latest.controlled_terms.MolecularEntity",
                "openminds.latest.controlled_terms.MuscularStructure",
                "openminds.latest.controlled_terms.NervousSystemStructure",
                "openminds.latest.controlled_terms.OlfactoryStimulusType",
                "openminds.latest.controlled_terms.OperatingDevice",
                "openminds.latest.controlled_terms.OperatingSystem",
                "openminds.latest.controlled_terms.OperationalApproach",
                "openminds.latest.controlled_terms.OpticalStimulusType",
                "openminds.latest.controlled_terms.Organ",
                "openminds.latest.controlled_terms.OrganSystemStructure",
                "openminds.latest.controlled_terms.OrganismSubstance",
                "openminds.latest.controlled_terms.OrganismSystem",
                "openminds.latest.controlled_terms.OrganizationType",
                "openminds.latest.controlled_terms.PatchClampVariation",
                "openminds.latest.controlled_terms.PaymentModelType",
                "openminds.latest.controlled_terms.PreparationType",
                "openminds.latest.controlled_terms.ProgrammingLanguage",
                "openminds.latest.controlled_terms.ProjectType",
                "openminds.latest.controlled_terms.PublicationStatus",
                "openminds.latest.controlled_terms.PulseShape",
                "openminds.latest.controlled_terms.QualitativeOverlap",
                "openminds.latest.controlled_terms.SemanticDataType",
                "openminds.latest.controlled_terms.SetupType",
                "openminds.latest.controlled_terms.SignalDirectionality",
                "openminds.latest.controlled_terms.SkeletalStructure",
                "openminds.latest.controlled_terms.SoftwareApplicationCategory",
                "openminds.latest.controlled_terms.SoftwareFeature",
                "openminds.latest.controlled_terms.SovereignState",
                "openminds.latest.controlled_terms.SpatialEncoding",
                "openminds.latest.controlled_terms.Species",
                "openminds.latest.controlled_terms.StimulationApproach",
                "openminds.latest.controlled_terms.StimulationTechnique",
                "openminds.latest.controlled_terms.SubcellularEntity",
                "openminds.latest.controlled_terms.SubjectAttribute",
                "openminds.latest.controlled_terms.SupranationalBody",
                "openminds.latest.controlled_terms.TactileStimulusType",
                "openminds.latest.controlled_terms.Technique",
                "openminds.latest.controlled_terms.TermSuggestion",
                "openminds.latest.controlled_terms.Terminology",
                "openminds.latest.controlled_terms.TissueSampleAttribute",
                "openminds.latest.controlled_terms.TissueSampleType",
                "openminds.latest.controlled_terms.TissueStructure",
                "openminds.latest.controlled_terms.TypeOfUncertainty",
                "openminds.latest.controlled_terms.UnitOfMeasurement",
                "openminds.latest.controlled_terms.VascularStructure",
                "openminds.latest.controlled_terms.VisualStimulusType",
                "openminds.latest.controlled_terms.WeightType",
            ],
            "keyword",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Significant word or concept that are representative of the software version.",
            instructions="Add all relevant keywords to this research product version either by adding controlled terms or by suggesting new terms. This value overrides the inherited value from the version-independent product.",
        ),
        Property(
            "languages",
            "openminds.latest.controlled_terms.Language",
            "language",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="System of communication (words, their pronunciation, and the methods of combining them) used and understood by a particular community.",
            instructions="Add all languages supported by this software version.",
        ),
        Property(
            "operating_devices",
            "openminds.latest.controlled_terms.OperatingDevice",
            "operatingDevice",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add all operating devices compatible with this software version.",
        ),
        Property(
            "operating_systems",
            "openminds.latest.controlled_terms.OperatingSystem",
            "operatingSystem",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Software that controls the operation of a computer and directs the processing of programs.",
            instructions="Add all operating systems supported by this software version.",
        ),
        Property(
            "output_formats",
            "openminds.latest.core.ContentType",
            "outputFormat",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Format of data that comes out of, is delivered or produced by a process or machine.",
            instructions="Add all content types that can be generated as output by this software version.",
        ),
        Property(
            "programming_languages",
            "openminds.latest.controlled_terms.ProgrammingLanguage",
            "programmingLanguage",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Distinct set of instructions for computer programs in order to produce various kinds of output.",
            instructions="Add all programming languages used to develop this software version.",
        ),
        Property(
            "publication_status",
            "openminds.latest.controlled_terms.PublicationStatus",
            "publicationStatus",
            description="no description available",
            instructions="Add the relevant publication status indicating the current lifecycle state of the resource (published, embargoed, disposed, retracted, etc.).",
        ),
        Property(
            "related_publications",
            [
                "openminds.latest.core.DOI",
                "openminds.latest.core.GenericIdentifier",
                "openminds.latest.core.HANDLE",
                "openminds.latest.core.ISBN",
                "openminds.latest.core.ISSN",
                "openminds.latest.publications.Book",
                "openminds.latest.publications.Chapter",
                "openminds.latest.publications.ScholarlyArticle",
            ],
            "relatedPublication",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Reference to something that was made available for the general public to see or buy.",
            instructions="Add all further publications besides the documentation that provide the original context for the production of this research product version (e.g., an original research article that used or produced the data of this research product version). This value overrides the inherited value from the version-independent product.",
        ),
        Property(
            "release_date",
            date,
            "releaseDate",
            required=True,
            description="Fixed date on which a product is due to become or was made available for the general public to see or buy",
            instructions="Enter the date (actual or intended) on which this research product version was first release, formatted as 'YYYY-MM-DD'.",
        ),
        Property(
            "repository",
            "openminds.latest.core.FileRepository",
            "repository",
            description="Place, room, or container where something is deposited or stored.",
            instructions="Add the file repository of this research product version.",
        ),
        Property(
            "scopes",
            [
                "openminds.latest.controlled_terms.AnalysisTechnique",
                "openminds.latest.controlled_terms.ContributionType",
                "openminds.latest.controlled_terms.DataType",
                "openminds.latest.controlled_terms.ExperimentalApproach",
                "openminds.latest.controlled_terms.OperationalApproach",
                "openminds.latest.controlled_terms.SoftwareApplicationCategory",
                "openminds.latest.controlled_terms.SoftwareFeature",
                "openminds.latest.controlled_terms.Technique",
                "openminds.latest.controlled_terms.TermSuggestion",
            ],
            "scope",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="Extent of something.",
            instructions="Add terms that describe what this software version does.",
        ),
        Property(
            "short_name",
            str,
            "shortName",
            formatting="text/plain",
            required=True,
            description="Shortened or fully abbreviated name of the software version.",
            instructions="Enter a short name (or alias) for this research product version that could be used as a shortened display title (e.g., for web services with too little space to display the full name). This value overrides the inherited value from the version-independent product.",
        ),
        Property(
            "support_channels",
            str,
            "supportChannel",
            multiple=True,
            unique_items=True,
            min_items=1,
            formatting="text/plain",
            description="Way of communication used to interact with users or customers.",
            instructions="Enter all channels through which a user can receive support for handling this research product version. This value overrides the inherited value from the version-independent product.",
        ),
        Property(
            "usage_conditions",
            ["openminds.latest.core.License", "openminds.latest.core.UsageAgreement"],
            "usageCondition",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add all licenses and available data usage agreements applicable to this product version.",
        ),
        Property(
            "version_identifier",
            str,
            "versionIdentifier",
            formatting="text/plain",
            required=True,
            description="Term or code used to identify the version of something.",
            instructions="Enter the version identifier of this research product version.",
        ),
        Property(
            "version_specification",
            str,
            "versionSpecification",
            formatting="text/plain",
            required=True,
            description="no description available",
            instructions="Enter a short description (or summary) of the novelties/peculiarities of this research product version in comparison to its preceding versions. If this research product version is the first version, you can enter the following disclaimer 'This is the first version of this research product'.",
        ),
    ]

    def __init__(
        self,
        id=None,
        accessibility=None,
        contributions=None,
        contributor_affiliations=None,
        copyright=None,
        dependencys=None,
        description=None,
        digital_identifier=None,
        documentation=None,
        full_name=None,
        funding=None,
        homepage=None,
        how_to_cite=None,
        implementss=None,
        input_formats=None,
        is_preceded_by=None,
        is_variant_of=None,
        is_version_of=None,
        keywords=None,
        languages=None,
        operating_devices=None,
        operating_systems=None,
        output_formats=None,
        programming_languages=None,
        publication_status=None,
        related_publications=None,
        release_date=None,
        repository=None,
        scopes=None,
        short_name=None,
        support_channels=None,
        usage_conditions=None,
        version_identifier=None,
        version_specification=None,
    ):
        return super().__init__(
            id=id,
            accessibility=accessibility,
            contributions=contributions,
            contributor_affiliations=contributor_affiliations,
            copyright=copyright,
            dependencys=dependencys,
            description=description,
            digital_identifier=digital_identifier,
            documentation=documentation,
            full_name=full_name,
            funding=funding,
            homepage=homepage,
            how_to_cite=how_to_cite,
            implementss=implementss,
            input_formats=input_formats,
            is_preceded_by=is_preceded_by,
            is_variant_of=is_variant_of,
            is_version_of=is_version_of,
            keywords=keywords,
            languages=languages,
            operating_devices=operating_devices,
            operating_systems=operating_systems,
            output_formats=output_formats,
            programming_languages=programming_languages,
            publication_status=publication_status,
            related_publications=related_publications,
            release_date=release_date,
            repository=repository,
            scopes=scopes,
            short_name=short_name,
            support_channels=support_channels,
            usage_conditions=usage_conditions,
            version_identifier=version_identifier,
            version_specification=version_specification,
        )
