from .stock_number import StockNumber
from .doi import DOI
from .swhid import SWHID
from .orcid import ORCID
from .rorid import RORID
from .issn import ISSN
from .rrid import RRID
from .handle import HANDLE
from .identifiers_dot_org_id import IdentifiersDotOrgID
from .gridid import GRIDID
from .isbn import ISBN
