"""
<description not available>
"""

# this file was auto-generated!

from datetime import datetime, time

from openminds.base import LinkedMetadata
from openminds.properties import Property


class DynamicMRIAcquisition(LinkedMetadata):
    """
    <description not available>
    """

    type_ = "https://openminds.om-i.org/types/DynamicMRIAcquisition"
    context = {"@vocab": "https://openminds.om-i.org/props/"}
    schema_version = "v5.0"

    properties = [
        Property(
            "behavioral_protocols",
            "openminds.v5.core.BehavioralProtocol",
            "behavioralProtocol",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="no description available",
            instructions="Add the behavioral protocol or protocols applied during this acquisition, including all tasks or observed behavioral conditions (for example, resting state).",
        ),
        Property(
            "contrast_agents",
            "openminds.v5.chemicals.AmountOfChemical",
            "contrastAgent",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add the contrast agent(s) administered for this acquisition, including for each the agent identity and administered amount; if no contrast agent was used, leave this field null. Include all agents given prior to or during the scan.",
        ),
        Property(
            "custom_property_sets",
            "openminds.v5.core.CustomPropertySet",
            "customPropertySet",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add any user-defined parameters grouped in context-specific sets that are not covered in the standardized properties of this activity.",
        ),
        Property(
            "delay_time",
            "openminds.v5.core.QuantitativeValue",
            "delayTime",
            description="no description available",
            instructions="Enter the delay time, defined as the time interval between a protocol-defined reference event (for example, stimulus onset, contrast administration, or physiological trigger) and the start of dynamic image acquisition, expressed in seconds. This value should reflect the actual timing applied during the scan.",
        ),
        Property(
            "description",
            str,
            "description",
            formatting="text/markdown",
            multiline=True,
            description="Longer statement or account giving the characteristics of the dynamic m r i acquisition.",
            instructions="Enter a description of this activity.",
        ),
        Property(
            "device",
            "openminds.v5.neuroimaging.MRIScannerUsage",
            "device",
            required=True,
            description="Piece of equipment or mechanism (hardware) designed to serve a special purpose or perform a special function.",
            instructions="Add the magnetic resonance imaging (MRI) scanner used for this acquisition. This reference should identify the specific device configuration under which the scan was performed.",
        ),
        Property(
            "distortion_corrections",
            "openminds.v5.core.File",
            "distortionCorrection",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add the distortion correction data used for this acquisition, linking to the calibration files applied during image reconstruction or post-processing. If no distortion correction was performed, leave this field null.",
        ),
        Property(
            "end_time",
            [datetime, time],
            "endTime",
            description="no description available",
            instructions="Enter the date and/or time on when this activity ended, formatted as either '2023-02-07T16:00:00+00:00' (date-time) or '16:00:00+00:00' (time).",
        ),
        Property(
            "inputs",
            ["openminds.v5.core.SubjectState", "openminds.v5.core.TissueSampleState"],
            "input",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="Something or someone that is put into or participates in a process or machine.",
            instructions="Add the specimen (subject or tissue sample) in the physical and biological state in which it was scanned, referencing the corresponding specimen record at the time of imaging.",
        ),
        Property(
            "is_part_of",
            "openminds.v5.core.DatasetVersion",
            "isPartOf",
            required=True,
            description="Reference to the ensemble of multiple things or beings.",
            instructions="Add the dataset version in which this activity was conducted.",
        ),
        Property(
            "lookup_label",
            str,
            "lookupLabel",
            formatting="text/plain",
            description="no description available",
            instructions="Enter a lookup label for this activity that may help you to find this instance more easily.",
        ),
        Property(
            "motion_corrections",
            "openminds.v5.core.File",
            "motionCorrection",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add the motion correction data used for this acquisition, linking to the calibration files or reference images applied during image reconstruction or post-processing. If no motion correction was performed, leave this field null.",
        ),
        Property(
            "number_of_discarded_volumes",
            int,
            "numberOfDiscardedVolumes",
            description="no description available",
            instructions="Enter the number of image volumes discarded by the operator or analyst prior to post-processing, including initial equilibration volumes and any later volumes removed due to artifacts or instability. This value should reflect the total user-defined exclusion applied after acquisition.",
        ),
        Property(
            "outputs",
            "openminds.v5.core.File",
            "output",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="Something or someone that comes out of, is delivered or produced by a process or machine.",
            instructions="Add the output data generated by this acquisition by linking to one or more files containing the primary imaging outputs and/or, if applicable, any secondary reconstructed or corrected outputs produced during post-processing.",
        ),
        Property(
            "performed_by",
            ["openminds.v5.computation.SoftwareAgent", "openminds.v5.core.Person"],
            "performedBy",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add all agents that performed this activity.",
        ),
        Property(
            "preparation_design",
            "openminds.v5.controlled_terms.PreparationType",
            "preparationDesign",
            description="no description available",
            instructions="Add the initial preparation type for this activity.",
        ),
        Property(
            "protocols",
            "openminds.v5.core.Protocol",
            "protocol",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="Plan that describes the process of a scientific or medical experiment, treatment, or procedure.",
            instructions="Add all protocols used during this activity.",
        ),
        Property(
            "registration_data",
            "openminds.v5.core.File",
            "registrationData",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add the registration data used for this acquisition, linking to the transformation and/or reference files applied during image alignment in post-processing. If no registration was performed, leave this field null.",
        ),
        Property(
            "specimen_orientation",
            "openminds.v5.controlled_terms.AnatomicalAxesOrientation",
            "specimenOrientation",
            required=True,
            description="no description available",
            instructions="Add the specimen orientation as the anatomical directions corresponding to the scanner X, Y, and Z axes, describing the alignment of the specimen's anatomy with the scanner coordinate system. Note that this orientation may differ from the prescribed slice orientation, especially in nonstandard specimen positioning.",
        ),
        Property(
            "start_time",
            [datetime, time],
            "startTime",
            description="no description available",
            instructions="Enter the date and/or time on when this activity started, formatted as either '2023-02-07T16:00:00+00:00' (date-time) or '16:00:00+00:00' (time).",
        ),
        Property(
            "study_targets",
            [
                "openminds.v5.controlled_terms.AnatomicalCavity",
                "openminds.v5.controlled_terms.AuditoryStimulusType",
                "openminds.v5.controlled_terms.BiologicalOrder",
                "openminds.v5.controlled_terms.BiologicalSex",
                "openminds.v5.controlled_terms.BreedingType",
                "openminds.v5.controlled_terms.CellCultureType",
                "openminds.v5.controlled_terms.CellType",
                "openminds.v5.controlled_terms.DeviceType",
                "openminds.v5.controlled_terms.Disease",
                "openminds.v5.controlled_terms.DiseaseModel",
                "openminds.v5.controlled_terms.ElectricalStimulusType",
                "openminds.v5.controlled_terms.ExternalBodyRegion",
                "openminds.v5.controlled_terms.GeneticStrainType",
                "openminds.v5.controlled_terms.GustatoryStimulusType",
                "openminds.v5.controlled_terms.Handedness",
                "openminds.v5.controlled_terms.MolecularEntity",
                "openminds.v5.controlled_terms.MuscularStructure",
                "openminds.v5.controlled_terms.NervousSystemStructure",
                "openminds.v5.controlled_terms.OlfactoryStimulusType",
                "openminds.v5.controlled_terms.OpticalStimulusType",
                "openminds.v5.controlled_terms.Organ",
                "openminds.v5.controlled_terms.OrganSystemStructure",
                "openminds.v5.controlled_terms.OrganismSubstance",
                "openminds.v5.controlled_terms.OrganismSystem",
                "openminds.v5.controlled_terms.SkeletalStructure",
                "openminds.v5.controlled_terms.Species",
                "openminds.v5.controlled_terms.SubcellularEntity",
                "openminds.v5.controlled_terms.TactileStimulusType",
                "openminds.v5.controlled_terms.TermSuggestion",
                "openminds.v5.controlled_terms.TissueSampleType",
                "openminds.v5.controlled_terms.TissueStructure",
                "openminds.v5.controlled_terms.VascularStructure",
                "openminds.v5.controlled_terms.VisualStimulusType",
                "openminds.v5.sands.CustomAnatomicalEntity",
                "openminds.v5.sands.ParcellationEntity",
                "openminds.v5.sands.ParcellationEntityVersion",
            ],
            "studyTarget",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Structure or function that was targeted within a study.",
            instructions="Add all study targets of this activity.",
        ),
        Property(
            "target_anatomy",
            [
                "openminds.v5.controlled_terms.AnatomicalCavity",
                "openminds.v5.controlled_terms.CellType",
                "openminds.v5.controlled_terms.ExternalBodyRegion",
                "openminds.v5.controlled_terms.MuscularStructure",
                "openminds.v5.controlled_terms.NervousSystemStructure",
                "openminds.v5.controlled_terms.Organ",
                "openminds.v5.controlled_terms.OrganSystemStructure",
                "openminds.v5.controlled_terms.OrganismSubstance",
                "openminds.v5.controlled_terms.OrganismSystem",
                "openminds.v5.controlled_terms.SkeletalStructure",
                "openminds.v5.controlled_terms.SubcellularEntity",
                "openminds.v5.controlled_terms.TissueStructure",
                "openminds.v5.controlled_terms.VascularStructure",
                "openminds.v5.sands.CustomAnatomicalEntity",
                "openminds.v5.sands.ParcellationEntity",
                "openminds.v5.sands.ParcellationEntityVersion",
            ],
            "targetAnatomy",
            description="no description available",
            instructions="Add the target anatomy, indicating the primary anatomical structure or region intended to be imaged in this acquisition. This field describes the imaging objective (for example, organ, tissue, or structure) and may be derived from the acquisition protocol description.",
        ),
        Property(
            "volume_acquisition_time",
            "openminds.v5.core.QuantitativeValue",
            "volumeAcquisitionTime",
            required=True,
            description="no description available",
            instructions="Enter the volume acquisition time, defined as the time required to acquire a single image volume, expressed in seconds. This value is typically equivalent to the repetition time for volume-based acquisitions and can be retrieved from the sequence timing information in the DICOM header.",
        ),
        Property(
            "volume_timing",
            "openminds.v5.core.QuantitativeValueArray",
            "volumeTiming",
            description="no description available",
            instructions="Enter the volume timing as an array specifying the acquisition time of each volume relative to the start of the dynamic scan, expressed in seconds, with one entry per acquired volume. These values may be derived from the repetition time or extracted from the acquisition metadata.",
        ),
    ]

    def __init__(
        self,
        id=None,
        behavioral_protocols=None,
        contrast_agents=None,
        custom_property_sets=None,
        delay_time=None,
        description=None,
        device=None,
        distortion_corrections=None,
        end_time=None,
        inputs=None,
        is_part_of=None,
        lookup_label=None,
        motion_corrections=None,
        number_of_discarded_volumes=None,
        outputs=None,
        performed_by=None,
        preparation_design=None,
        protocols=None,
        registration_data=None,
        specimen_orientation=None,
        start_time=None,
        study_targets=None,
        target_anatomy=None,
        volume_acquisition_time=None,
        volume_timing=None,
    ):
        return super().__init__(
            id=id,
            behavioral_protocols=behavioral_protocols,
            contrast_agents=contrast_agents,
            custom_property_sets=custom_property_sets,
            delay_time=delay_time,
            description=description,
            device=device,
            distortion_corrections=distortion_corrections,
            end_time=end_time,
            inputs=inputs,
            is_part_of=is_part_of,
            lookup_label=lookup_label,
            motion_corrections=motion_corrections,
            number_of_discarded_volumes=number_of_discarded_volumes,
            outputs=outputs,
            performed_by=performed_by,
            preparation_design=preparation_design,
            protocols=protocols,
            registration_data=registration_data,
            specimen_orientation=specimen_orientation,
            start_time=start_time,
            study_targets=study_targets,
            target_anatomy=target_anatomy,
            volume_acquisition_time=volume_acquisition_time,
            volume_timing=volume_timing,
        )
